name: Build and deploy Node.js app to Azure Web App - NATLab-Quiz-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install, build, and test
        run: |
          cd server
          npm install
          npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: 'Deploy backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NATLab-Quiz-Test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D30591AFD1D14E1F8C90800D46FAF92E }}
